Princess work!
juliasangrim/c_sharp pull request #1
Opened 2022-09-16 06:49 UTC by juliasangrim

2022-09-17 15:18 UTC, Ningyo requested changes

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +
лишние переводы строк. достаточно одного

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +        List<string> contenderNames = (from fName in _firstName from sName in _lastName select fName + " " + sName).ToList();
1. сложные конструкции лучше писать в несколько строк, разделяя по смыслу. читать в одну строку довольно сложно + строка может получиться довольно длинной и не влезть в один экран:
from fName in _firstName
from sName in _lastName
2. можно использовать [интерполяцию строк](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation) - смотрится аккуратнее, читать легче.
3. вместо объявления полного типа List<string> здесь можно использовать просто var, т.к. инициализируем тут же

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +    private static string[] _firstName = {"Ben", "Bart", "Carter", "Rufus", "Dan", "Chuck", "Nate", "Eric", "Jack", "Cyrus"};
здесь и ниже: имя списка должно звучать во множественном числе, так легче понимать просто по названию, что речь идёт о каком-то списке. _firstName**s**

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +        List<string> contenderNames = (from fName in _firstName from sName in _lastName select fName + " " + sName).ToList();
немного неочевидно, что претендентов получится ровно 100 - нужно для этого какие-то усилия приложить и пересчитать кол-во имён и фамилий. в принципе, мы по условию знаем, что их всегда 100, и кол-во меняться не будет, так что можно оставить комментарий с пояснением. но тогда нужно как-то согласовать это с тем, что кол-во претендентов указывается в корне программы и передаётся в холл - чисто в теории в этом месте может произойти ошибка, если изменить значение countContender. немного не хорошо получается, что одна часть программы как будто знает и так эту константу, а другая - нет.

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/Program.cs
> +    const int countContender = 100;
звучит как название функции "посчитай претендентов", тогда как константа должна быть существительным - "количество претендентов" contenderCount

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Contender.cs
> +    private string _name;
хорошо было бы добавлять саммари к полям и функциям - это хорошая привычка. да, хорошее название много говорит само, но в саммари можно дописать пояснения, например, что имя уникально. если представить, что это была бы боевая задача, то к этому коду пришлось бы возвращаться через некоторое время, и очевидные сейчас вещи могут забыться через несколько месяцев. комментарии и саммари экономят время в будущем

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Contender.cs
> +    private int _matchScore;
не самое очевидное название, на мой взгляд) не очень понятно в контексте задачи про принцессу и женитьбу, что это за счёт матча

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +    public List<Contender> PassedContenders { get; }
поля хорошо размещать в самом верху, до любых функций.

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +
лишняя пустая строка

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +    public bool IsHeBest(Contender contender, Contender? bestContender)
1. по условию задачи подруга может сравнить только двух претендентов, которых принцесса уже видела (т.е. он либо уже ушёл, либо стоит сейчас перед ней). не вижу здесь этой проверки
2. bestContender - не самое удачное имя. оно как будто говорит, что мы уже знаем, что второй претендент - лучший

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Hall.cs
> +            allContenders.Add(new Contender(contenderNames[i - 1], i));
потенциальное место для ошибки, если в contenderNames окажется меньше countContenders элементо

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Hall.cs
> +    private static List<Contender> MixContenders(IList<Contender> contenders)
имеет место быть, но можно написать короче без использования второго списка

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Hall.cs
> +
лишняя пустая строка

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Hall.cs
> +    public List<Contender> AllContenders
можно сделать проперти с приватным сеттером и не писать лишний код

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +
лишние пустые строки

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +    public Princess(Friend friend, Hall hall)
не хватает пустой строки, чтобы отлепить поля от конструктора

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +    public Princess(Friend friend, Hall hall)
хорошо бы завести интерфейсы, чтобы принцесса не зависела от конкретных реализаций. будет лучше соответствовать принципам SOLID и тестировать будет проще

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +            if (_prince.MatchScore > IStrategy.MaxMatchScore / 2 )
меня очень смущает, что принцесса может просто взять  и спросить у претендента, сколько он стоит. с одной стороны, принцесса не должна знать количественную характеристику принца - иначе что ей мешает схитрить и просто узнать её в процессе выбора. с другой, нужно как-то уметь считать уровень счастья, что вроде вы похоже на ответственность принцессы. мне кажется, над этим моментом стоит подумать.

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +        if (_prince != null)
лучше избегать больших и вложенных ифов - их сложно воспринимать. думаю, здесь можно несколько раз инвертировать ифы и получить более "плоскую" и читабельную логику

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/strategy/Strategy.cs
> +
лишняя пустая строка

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/strategy/Strategy.cs
> +            _friend.AddPassedContender(newContender);
не очень согласуется с тем, что в подруге параметр называется отвергнутым претендентом. думаю, в подруге стоит переименовать

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/strategy/Strategy.cs
> +    private Friend _friend;
хорошо бы сделать readonly то, что в процессе жизни точно не планируется менять

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/strategy/Strategy.cs
> +                if (_friend.IsHeBest(newContender, _bestContender))
по названию не очень понятно, в чью сторону идёт сравнение - кто из двух лучше, если подруга ответила true?

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +    public int CountHappy()
безобидное название, по которому не понятно, что в процессе происходит самая важная часть - выбор. честно говоря, прочтение кода "создали невесту, посчитали её счастье" вызывает недоумение: "что за магия произошла между этими двумя строчками, и как я это пропустила?"

2022-09-17 15:18 UTC, Ningyo commented on princess_choice/princess_choice/strategy/IStrategy.cs
> +    public const int MaxMatchScore  = 100;
в коде несколько раз встречается это значение - это не очень хорошо. велик риск, что при изменении в одном месте можно забыть про другое, и логика посыпется, т.к. мы знаем, что это одно и то же значение, но формально они никак не связаны.

2022-09-25 05:55 UTC, Ningyo commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +        List<string> contenderNames = (from fName in _firstName from sName in _lastName select fName + " " + sName).ToList();
увидела саммари. пусть будет так

2022-09-25 06:00 UTC, Ningyo requested changes

2022-09-25 06:00 UTC, Ningyo commented on princess_choice/princess_choice/model/Contender.cs
> +    public int MatchScore
можно использовать просто проперти с приватным сеттером - меньше места займёт

2022-09-25 12:29 UTC, juliasangrim commented on princess_choice/princess_choice/Program.cs
> +    const int countContender = 100;
убрала совсем эту константу

2022-09-25 12:29 UTC, juliasangrim commented on princess_choice/princess_choice/model/Contender.cs
> +    private string _name;
добавила

2022-09-25 12:29 UTC, juliasangrim commented on princess_choice/princess_choice/model/Contender.cs
> +    private int _matchScore;
поменяла, но все еще неуверена, а идей больше нет)

2022-09-25 12:30 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +    public List<Contender> PassedContenders { get; }
переместила

2022-09-25 12:30 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +
убрала

2022-09-25 12:31 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +    public bool IsHeBest(Contender contender, Contender? bestContender)
поменяла все названия и добавила саммари, и внутри появилась проверка на то, что пертендент из тех, кто уже был у принцессы

2022-09-25 12:32 UTC, juliasangrim commented on princess_choice/princess_choice/model/Hall.cs
> +            allContenders.Add(new Contender(contenderNames[i - 1], i));
теперь зависит только от списка, который изначально сгенерирован

2022-09-25 12:33 UTC, juliasangrim commented on princess_choice/princess_choice/model/Hall.cs
> +    private static List<Contender> MixContenders(IList<Contender> contenders)
переписала

2022-09-25 12:33 UTC, juliasangrim commented on princess_choice/princess_choice/model/Hall.cs
> +
убрала

2022-09-25 12:33 UTC, juliasangrim commented on princess_choice/princess_choice/model/Hall.cs
> +    public List<Contender> AllContenders
вообще убрала его, потому что он неиспользуется нигде

2022-09-25 12:34 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +
убрала

2022-09-25 12:34 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +    public Princess(Friend friend, Hall hall)
добавила

2022-09-25 12:36 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +    public Princess(Friend friend, Hall hall)
завела интерфесы, но не очень уверена в интерфейсе контендера

2022-09-25 12:36 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +        if (_prince != null)
переделала

2022-09-25 12:38 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/Strategy.cs
> +
убарала

2022-09-25 12:38 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/Strategy.cs
> +            _friend.AddPassedContender(newContender);
переименовала

2022-09-25 12:38 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/Strategy.cs
> +    private Friend _friend;
сделала

2022-09-25 12:39 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/Strategy.cs
> +                if (_friend.IsHeBest(newContender, _bestContender))
написала саммари и переименовала, чтобы было понятно(вроде)

2022-09-25 12:39 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +    public int CountHappy()
разделила на 2 метода, теперь там CountHappy() и ChoosePrince()

2022-09-25 12:42 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +            if (_prince.MatchScore > IStrategy.MaxMatchScore / 2 )
я очень долго думала и не придумала, как сделать так, чтобы принцесса не знала количественную характеристику принца. 
была идея просто убрать его из принцессы и спрашивать его количественную характеристику у подруги, но получается тоже самое, только через подругу.

2022-09-25 12:42 UTC, juliasangrim commented on princess_choice/princess_choice/model/Contender.cs
> +    public int MatchScore
переделала

2022-09-25 12:44 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/IStrategy.cs
> +    public const int MaxMatchScore  = 100;
не знаю, как не привязываться к этому значению, кроме как, возможно, считать изначально какая максимальная количественная характеристика у принца, потому что на этом завязана стратегия

2022-10-04 09:00 UTC, Ningyo commented on princess_choice/princess_choice/strategy/IStrategy.cs
> +    public const int MaxMatchScore = 100;
лучше бы или везде смотреть на одну константу, или везде отталкиваться от фактического кол-ва претендентов.

2022-10-04 09:00 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +        if (!PassedContenders.Contains(_lastBestContender))
currContender

2022-10-04 09:00 UTC, Ningyo commented on princess_choice/princess_choice/model/Hall.cs
> +    private static List<Contender> MixContenders(IList<Contender> contenders)
можно ещё короче

2022-10-04 09:43 UTC, juliasangrim commented on princess_choice/princess_choice/model/Hall.cs
> +    private static List<Contender> MixContenders(IList<Contender> contenders)
сделала еще короче

2022-10-04 09:50 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +        if (!PassedContenders.Contains(_lastBestContender))
в итоге мне здесь не нужна проверка, потому что currContender это принц, который сейчас у принцессы, и он решает оставлять его или нет, и уже после этой проверки я его добавляю в лист passsedContenders, если он принцессе не понравился

2022-10-04 10:18 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +            if (_prince.MatchScore > IStrategy.MaxMatchScore / 2 )
вроде переделала

2022-10-07 09:06 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/IStrategy.cs
> +    public const int MaxMatchScore = 100;
переделала

2022-10-09 03:27 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +            if (_prince.MatchScore > IStrategy.MaxMatchScore / 2 )
о, интересно получилось) один только момент - надо подумать, насколько валидна ситуация, что мы можем спросить принцессу, насколько она счастлива, ещё до запуска выбора принца, и получим 10. в общем-то условию задачи это вроде не противоречит, но обычно стоит защищаться от неправильного использования кода. можно кидать ошибку, если никакого выбора ещё не было. но это опционально) или хотя бы в тестах задокументировать потом, что есть вот такой кейс.

2022-10-09 03:43 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +        foreach (var contender in PassedContenders)
не обязательно "вручную" проходиться по списку. можно использовать стандартные методы, FirstOrDefault, например

2022-10-09 03:43 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +        if (!PassedContenders.Contains(_lastBestContender))
то, что вы убрали проверку - не соответствует условию задачи. по условию подруга может сравнивать только претендентов, которых принцесса видела. нельзя просто поверить, что currContender - это тот, который сейчас у принцессы

2022-10-09 03:50 UTC, Ningyo requested changes

2022-10-09 03:50 UTC, Ningyo commented on princess_choice/princess_choice/Program.cs
> +            writetext.WriteLine(contender + " " + contender.Value);
можно использовать [интерполяцию строк](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation) - красивее будет

2022-10-09 03:50 UTC, Ningyo commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +
лишняя пустая строка

2022-10-09 03:50 UTC, Ningyo commented on princess_choice/princess_choice/model/Hall.cs
> +        var contenderNames = ContenderNameGenerator.GenerateNames();
небольшое замечание - в вашем случае у вас генерация претендентов действительно довольно безобидная, т.к. вы не читаете ни из каких файлов или баз их имена. но в общем случае в конструкторе лучше размещать самую примитивную логику - инициализацию значениями из параметров или элементарную инициализацию вроде пустых списков и т.п.

2022-10-09 07:55 UTC, juliasangrim commented on princess_choice/princess_choice/model/Hall.cs
> +        var contenderNames = ContenderNameGenerator.GenerateNames();
переделала

2022-10-09 07:55 UTC, juliasangrim commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +
убрала

2022-10-09 07:56 UTC, juliasangrim commented on princess_choice/princess_choice/Program.cs
> +            writetext.WriteLine(contender + " " + contender.Value);
переделала

2022-10-09 07:56 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +        foreach (var contender in PassedContenders)
переделала

2022-10-09 07:58 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +        if (!PassedContenders.Contains(_lastBestContender))
а, поняла, хорошо, переделала

2022-10-10 12:41 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +        foreach (var contender in PassedContenders)
есть небольшая особенность с .Contains(currContender). представим, что у нас есть Иван Иванович 10. что будет, если он уже находится в PassedContenders, и вы сделаете PassedContenders.Contains(new Contender("Иван Иванович", 10))?

2022-10-10 13:55 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +        foreach (var contender in PassedContenders)
он не найдется, что-то не подумала, надо переделать

2022-10-10 14:07 UTC, juliasangrim commented on princess_choice/princess_choice/model/Friend.cs
> +        foreach (var contender in PassedContenders)
переделала

2022-10-10 15:26 UTC, Ningyo commented on princess_choice/princess_choice/model/Friend.cs
> +    public void RememberContenderIfBest(Contender currContender)
мне кажется, вот эту логику напротив можно было бы оставить внутри AddPassedContender. то, как подруга определяет лучшего претендента - это её внутреннее дело и её состояние. она не меняет здесь ничье чужое состояние, не меняет никаких публичных своих полей неожиданным образом. тем более что здесь никаких сложных процессов не происходит - она не обращается к внешним сервисам, не занимается никакой сложной математикой и т.п. чтобы можно было опасаться, что вызываем безобидную операцию, а можем упасть на ровном месте. в принципе такие команды по смене своего состояния извне допустимы, но разве что для отношений целое-часть. пока не могу придумать примера, когда бы один сервис имел право другому диктовать измениться)

2022-10-11 07:55 UTC, merged