Dev
juliasangrim/c_sharp pull request #2
Opened 2022-10-11 13:32 UTC by juliasangrim

2022-10-20 14:39 UTC, Ningyo requested changes

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/Program.cs
> +
лишняя пустая строка

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/Program.cs
> +
лишняя пустая строка

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +    ContenderNameGenerator()
зачем вам нужен этот конструктор?

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +        _strategy = new Strategy(friend, hall, writer);
вы можете сразу стратегию передать в конструктор принцессе

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/model/Princess.cs
> +        var happiness = CountHappy();
не очень понимаю, зачем разрывать логику на две функции)

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/strategy/Strategy.cs
>  namespace princess_choice.strategy;
заметила только сейчас - это же сишный стиль) нехорошо сишный стиль вносить

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/strategy/Strategy.cs
> +            _writer.Write(currContender.Name + " " + currContender.Value);
интерполяция строк будет аккуратнее смотреться)

2022-10-20 14:39 UTC, Ningyo commented on princess_choice/princess_choice/writer/ContenderWriter.cs
> +        File.Delete(_fileName);
не то, чего можно ожидать от конструктора. думается, конструктор выполнит какую-то базовую инициализацию, а он в файловую систему лезет удалять файл - есть этот файл или нет, занят он или нет - ничего не знаем, опасное место получается

2022-10-23 09:45 UTC, juliasangrim commented on princess_choice/princess_choice/Program.cs
> +
убрала

2022-10-23 09:45 UTC, juliasangrim commented on princess_choice/princess_choice/Program.cs
> +
убрала

2022-10-23 09:46 UTC, juliasangrim commented on princess_choice/princess_choice/generator/ContenderNameGenerator.cs
> +    ContenderNameGenerator()
убрала

2022-10-23 09:46 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +        _strategy = new Strategy(friend, hall, writer);
вынесла

2022-10-23 09:47 UTC, juliasangrim commented on princess_choice/princess_choice/model/Princess.cs
> +        var happiness = CountHappy();
просто показалось логичным, но я все в одну функцию сделала сейчас

2022-10-23 09:48 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/Strategy.cs
>  namespace princess_choice.strategy;
а имелось в виду, что названия в сишном стиле? если да, то переименовала вроде все

2022-10-23 09:48 UTC, juliasangrim commented on princess_choice/princess_choice/strategy/Strategy.cs
> +            _writer.Write(currContender.Name + " " + currContender.Value);
переделала

2022-10-23 09:48 UTC, juliasangrim commented on princess_choice/princess_choice/writer/ContenderWriter.cs
> +        File.Delete(_fileName);
вынесла в отдельный метод

2022-10-23 10:23 UTC, Ningyo requested changes

2022-10-23 10:23 UTC, Ningyo commented on princess_choice/PrincessChoice/Writer/ContenderWriter.cs
> +        using var output = new StreamWriter(_fileName ?? throw new NullReferenceException(), true);
1.хм. если вам нужно имя настолько, что работать без него нельзя - можно в конструкторе это сразу проверить, только текст ошибке дописать понятный. чтобы понятно было, что это за ексепшн такой
2.с пустым именем файла можно работать, если уж за проверку взялись?) он же может быть "" или "   ", например

2022-10-23 10:23 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Princess.cs
> +        var happiness = 10;
magic number) в приватные константы хотя бы нужно вынести и дать понятное название

2022-10-23 17:14 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Princess.cs
> +        var happiness = 10;
вынесла

2022-10-23 17:14 UTC, juliasangrim commented on princess_choice/PrincessChoice/Writer/ContenderWriter.cs
> +        using var output = new StreamWriter(_fileName ?? throw new NullReferenceException(), true);
переделала

2022-10-25 07:51 UTC, Ningyo commented on princess_choice/PrincessChoice/Writer/ContenderWriter.cs
> +        using var output = new StreamWriter(_fileName ?? throw new NullReferenceException(), true);
проверьте, не включает ли проверка IsNullOrWhiteSpace в себя IsNullOrEmpty

2022-10-25 07:52 UTC, Ningyo commented on princess_choice/PrincessChoice/Writer/ContenderWriter.cs
> +        using var output = new StreamWriter(_fileName ?? throw new NullReferenceException(), true);
вижу исправление)

2022-10-25 07:53 UTC, Ningyo approved these changes

2022-10-25 07:53 UTC, merged