tests done
juliasangrim/c_sharp pull request #3
Opened 2022-10-25 08:43 UTC by juliasangrim

2022-10-30 06:09 UTC, Ningyo requested changes

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Friend.cs
> +    public Contender? LastBestContender { get; set; }
вы уверены, что здесь нужен публичный сеттер? теперь кто угодно в любой момент времени может лучшего претендента подруге поменять

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Friend.cs
> +    private List<Contender> PassedContenders { get; }
приватные поля именуются с _ и в camelCase; к тому же приватному полю не обязательно быть проперти - весь смысл проперти теряется) это может быть просто поле

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void BestContender_VisitedPrincess_Remember()
здесь и в подобных местах:
1.это сишным стилем попахивает)
2.название метода должно быть таким же говорящим, как во всём остальном коде. пока что непонятно, что значит "лучший претендент посещённая принцесса запомнить"

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +        ((Friend)_friend).LastBestContender.Should().NotBeNull();
если вы тестируете конкретный класс, можете сразу честно завести экземпляр этого класса. и не заниматься приведением

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +            .WithMessage("Current contender not visited princess!");
если есть время и желание, можете посмотреть, [как добавлять файлы ресурсов](https://learn.microsoft.com/en-us/visualstudio/ide/managing-application-resources-dotnet?view=vs-2022), и избавиться от меджиков таким образом. получится что-то вроде .WithMessage(PrincessResources.NotVisitedContenderComparisonError)

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void IsContenderBest_PrincessNotVisitByBestContender_ThrowError()
без описания или понятного названия не очень понятно, чем этот тест отличается от BestContender_NotVisitedPrincess_ThrowError

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +        _friend.AddPassedContender(worstContender);
у вас данные между тестами точно остаются корректными? просто подруга у вас одна и та же, и перед каждым тестом вы добавляете к ней худшего претендента. в тестах вы тоже можете добавлять претендентов. порядком выполнения тестов вы не управляете. получается, что будет в подруге перед каждым тестом, сказать нельзя

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/HallTest.cs
> +        _testHall.NextContender().Should().BeNull();
что здесь гарантирует, что в холле больше никого нет, чтобы получился такой результат?

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/PrincessTest.cs
> +    public void PrincessStrategy_BestContenderInSecondPart_PrincessUnhappy()
к сложным тестам хотелось бы описание, почему так должно получиться

2022-10-30 06:09 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/PrincessTest.cs
> +public class PrincessTest
у вас здесь ещё расчёт счастья для случая >50 можно проверить, а то вы только два варианта проверили

2022-10-31 16:12 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void BestContender_VisitedPrincess_Remember()
я согласна со втормы пунктом, но вот первый не понимаю, потому что в официальной документации названия пишут в таком же стиле: https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#best-practices

2022-11-01 08:38 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void BestContender_VisitedPrincess_Remember()
ммм хорошо, ссылка на документацию) хорошо, я просто привыкла в тестах к такому же +- стилю, как во всем остальном коде. тогда вопрос именно про нижние подчёркивания снимаю. второй остаётся актуальным. в документации всё же соблюдают формат {что сделать}_{при каких условиях\с какими значениями}_{что должно случиться\вернуться  should\returns}

2022-11-07 03:11 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Friend.cs
> +    public Contender? LastBestContender { get; set; }
вернула обратно

2022-11-07 03:12 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Friend.cs
> +    private List<Contender> PassedContenders { get; }
переименовала

2022-11-07 03:13 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void BestContender_VisitedPrincess_Remember()
переименовала

2022-11-07 03:14 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +        ((Friend)_friend).LastBestContender.Should().NotBeNull();
убрала эти тесты, там без ласт контендера их не протестить

2022-11-07 03:16 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +            .WithMessage("Current contender not visited princess!");
я попробовала добавить, но в итоге он ресурс находит, а строка почему-то все равно null :( очень долго сидела, и так и не поняла в чем проблема

2022-11-07 03:21 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void IsContenderBest_PrincessNotVisitByBestContender_ThrowError()
переименовала

2022-11-07 03:21 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +        _friend.AddPassedContender(worstContender);
сделала все в set up, чтобы перед каждый тестои запускалось заново

2022-11-07 03:22 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/HallTest.cs
> +        _testHall.NextContender().Should().BeNull();
перенесла инициализацию холла в setUp, он создается пустым изначально

2022-11-07 03:23 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/PrincessTest.cs
> +public class PrincessTest
добавила

2022-11-07 03:23 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/PrincessTest.cs
> +    public void PrincessStrategy_BestContenderInSecondPart_PrincessUnhappy()
добавила описание

2022-11-08 13:32 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +            .WithMessage("Current contender not visited princess!");
как-то странно) можем на паре посмотреть

2022-11-08 13:38 UTC, Ningyo requested changes

2022-11-08 13:38 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void CheckWhoBest_IfContenderBestAndPrincessNotVisitedByThisContender_ThrowError()
вижу проверку, если один претендент не посетил принцессу. у вас есть возможность проверить, что если оба не посетили, тоже будет ошибка?

2022-11-15 07:53 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +            .WithMessage("Current contender not visited princess!");
оказывается просто не там была строка написана.....

2022-11-15 07:53 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +    public void CheckWhoBest_IfContenderBestAndPrincessNotVisitedByThisContender_ThrowError()
нет

2022-11-15 15:08 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/FriendTest.cs
> +            .WithMessage("Current contender not visited princess!");
класс)) поищите в свободное время всё же, как в райдере с ресурсами работать. точно должен быть способ их  нормально отображать, а не голой xml'кой) если вы её руками правили, там, конечно, много где случайно накосячить можно

2022-11-15 15:08 UTC, merged