Lab 4 done!
juliasangrim/c_sharp pull request #4
Opened 2022-12-12 16:41 UTC by juliasangrim

2022-12-14 15:12 UTC, Ningyo requested changes

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/AttemptGenerator/Program.cs
> +using PostgresDbContext db = new PostgresDbContext(optionsBuilder.Options);
можно вроде использовать var - здесь и так понятно, какого типа будет

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/AttemptGenerator/WorldGenerator.cs
> +        db.SaveChanges();
1. функцию можно сделать асинхронной)
2. почему решили сделать статической?
3. вы проверяли, сколько запросов в бд в этой функции происходит? у mssql server есть функция дебага sql запросов, наверняка в постгресе тоже есть

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Context/PostgresDbContextFactory.cs
> +        var configuration = new ConfigurationBuilder()
почему у вас дважды повторяется конфигурация, здесь и в program?

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/DbModel/ContenderEntity.cs
> +///DTO for contender.
не совсем data transfer object) вы же даже названи entity. это у вас доменная сущность по сути. под дто подходит скорее то, что у вас холл в следующей задаче будет отдавать по http, например

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Mapper/ContendersListMapper.cs
> +            if (contenderEntity.SequenceNumber < contenderEntities.Count)
думаю, эту проверку лучше вынести до маппинга, вы же можете сразу понять, есть в списке неправильный претендент или нет, и не делать лишнюю работу по созданию новых претендентов

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Mapper/ContendersListMapper.cs
> +                listMapContenders.Insert(contenderEntity.SequenceNumber, contender);
можно не инсертить по одному, а сразу сделать contenderEntities.Select(x => ...)

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Mapper/ContendersListMapper.cs
> +public static class ContendersListMapper
у вас методы отсюда используются в нескольких местах? им точно нужно быть публичными, или можно их отнести всё же к приватной логике тех сервисов, которые их вызывают?
меня смущает, что здесь есть проверки и несколько неочевидная логика, которой в принципе могло бы не быть, если бы этот код располагался непосредственно рядом с местом своего вызова, и мог бы полагаться, что ему дают корректные входные данные. например, мне кажется, немного странно проверять при чтении, точно ли в бд корректные данные записаны. всё же если предполагать, что у вас code-first, то руками в базу лезть вообще незачем, и плохих данных там не может появиться, вы же сами их туда записываете. в общем, немного оверинжиниринг

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Migrations/20221212144748_CreateTableAttempts.cs
> +                    PrinceAttemptEntityId = table.Column<int>(type: "integer", nullable: true)
может принц без попытке существовать? почему nullable true?

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Executor.cs
> +        var attempts = _postgresDb.PrinceAttempt.ToList();
чтение-запись в бд обычно асинхронные

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Hall.cs
> +    public virtual void CallNextGroup(string? attemptName)
не очень понимаю, название попытки вы передаёте, но дальше не используете?

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/HallDb.cs
> +        else
можно сделать короче и с меньшим кол-вом скобок) вначале проверяете, если null и кидаете ошибку, дальше else и скобки писать не нужно, у вас после exception'а туда исполнение всё равно не дойдёт

2022-12-14 15:12 UTC, Ningyo commented on princess_choice/PrincessChoiceTest/TestHallAscending.cs
> +        var contenderCount = int.Parse(PrincessResource.ContenderCount);
хмм а зачем у вас кол-во претендентов в ресурсы попало? ресурсы - не настройки, они для строк и локализации) если вам нужен инт, можете его или в апп сеттинг поместить, или в константы

2022-12-17 18:21 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Executor.cs
> +        var attempts = _postgresDb.PrinceAttempt.ToList();
а нужно прям методы отдельно сделать на чтение запись, которые Task возвращают делать? или можно просто использовать на месте что-то типа await db.SaveChangesAsync()

2022-12-20 08:01 UTC, juliasangrim commented on princess_choice/AttemptGenerator/Program.cs
> +using PostgresDbContext db = new PostgresDbContext(optionsBuilder.Options);
переделала

2022-12-20 08:01 UTC, juliasangrim commented on princess_choice/PrincessChoice/DbModel/ContenderEntity.cs
> +///DTO for contender.
переделала

2022-12-20 08:02 UTC, juliasangrim commented on princess_choice/PrincessChoice/Mapper/ContendersListMapper.cs
> +                listMapContenders.Insert(contenderEntity.SequenceNumber, contender);
переделала

2022-12-20 08:02 UTC, juliasangrim commented on princess_choice/PrincessChoice/Migrations/20221212144748_CreateTableAttempts.cs
> +                    PrinceAttemptEntityId = table.Column<int>(type: "integer", nullable: true)
переделала

2022-12-20 08:02 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/HallDb.cs
> +        else
переделала

2022-12-20 08:02 UTC, juliasangrim commented on princess_choice/PrincessChoiceTest/TestHallAscending.cs
> +        var contenderCount = int.Parse(PrincessResource.ContenderCount);
переделала

2022-12-20 08:50 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Hall.cs
> +    public virtual void CallNextGroup(string? attemptName)
я использую ее в HallDB

2022-12-21 14:21 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Executor.cs
> +        var attempts = _postgresDb.PrinceAttempt.ToList();
имела в виду этот метод переделать на асинхронный) да, в т.ч. использовать SaveChanges**Async**

2022-12-21 14:27 UTC, Ningyo requested changes

2022-12-21 14:27 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Hall.cs
> +    public virtual void CallNextGroup(string? attemptName)
в этом методе в этом классе не вижу использования. имеете в виду, что есть HallDB и Hall с общим интерфейсом, но параметр используется в HallDB и не используется здесь? а сам класс холл у вас используется где-либо?

2022-12-21 14:27 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Executor.cs
> +        var attempts = _postgresDb.PrinceAttempt.Include(c => c.Contenders).ToListAsync();
await. тогда .Result уберётся

2022-12-21 14:54 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Hall.cs
> +    public virtual void CallNextGroup(string? attemptName)
нет, сейчас класс Hall не используется, он был до подключения к бд, я просто решила его ставить, ну чтобы было))) и да в Hall не используется, но т.к. они от одного интерфейса пришлось вставить и сюда

2022-12-24 15:00 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Executor.cs
> +        var attempts = _postgresDb.PrinceAttempt.Include(c => c.Contenders).ToListAsync();
сделала

2022-12-24 15:00 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Executor.cs
> +        var attempts = _postgresDb.PrinceAttempt.ToList();
сделала

2022-12-25 07:51 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Executor.cs
> +                        RunAllAttempt().Wait(cancellationToken);
а здесь зачем вы теперь ждёте?) можно же так же асинхронно запускать?

2022-12-25 07:51 UTC, Ningyo commented on princess_choice/PrincessChoice/Model/Hall.cs
> +    public virtual void CallNextGroup(string? attemptName)
тогда вы можете просто удалить старый холл, чтобы не хранить мёртвый код) если захотите на него посмотреть - он у вас в гите в истории всё равно останется

2022-12-26 15:55 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Hall.cs
> +    public virtual void CallNextGroup(string? attemptName)
там просто еще тесты написаны для этого холла, не очень хочется их тоже выпиливать если честно

2022-12-26 15:56 UTC, juliasangrim commented on princess_choice/PrincessChoice/Model/Executor.cs
> +                        RunAllAttempt().Wait(cancellationToken);
переделала

2022-12-27 08:43 UTC, merged